### PR TITLE
disablePrint option for print_summary() 

### PR DESCRIPTION
**Pull request by DaWe35**
## Description

Option disablePrint added for print_summary(), example:
`binance_websocket_api_manager.print_summary(add_string=your_text, disablePrint=True)`

## Motivation and Context

Printing every second is not the best, sometimes the screen flashes when printing is slow and errors get lost in plenty of printed text. I tried to do the windows update with curses, and I think it would be great to use curses in the examples too.

The only problem that I experienced (on windows 10) that color codes do not work with curses.
kép

```
def worker(window):
	while True:
		your_text = 'asd'
		printText = binance_websocket_api_manager.print_summary(add_string=your_text, disablePrint=True)
		window.addstr(0, 0, printText)
		window.refresh()
		time.sleep(1)

curses.wrapper(worker)

```

# PR Details

Tested and 100% backward compatible.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the 
**[CONTRIBUTING](https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/master/CONTRIBUTING.md)** 
document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by DaWe35** [comment]
While I can't use curses, it's not urgent for me to merge. Anyway, can we solve somehow colors in `curses`?

**Comment by oliver-zehentleitner** [comment]
Hi DaWe35!

Nice idea! Lets try it!

1. The code style is like "print_text" or "disable_print"

2. Is it possible to put the code 
```
def worker(window):
	while True:
		your_text = 'asd'
		printText = binance_websocket_api_manager.print_summary(add_string=your_text, disablePrint=True)
		window.addstr(0, 0, printText)
		window.refresh()
		time.sleep(1)

curses.wrapper(worker)
```
into the `print_summary()` function in a way we can reuse it in `print_stream_info()` too?

3. I think removing the color codes would be very simple by filtering `print_text` if os == win and `disable_print` is True. Removing color codes could work this way: https://stackoverflow.com/questions/30425105/filter-special-chars-such-as-color-codes-from-shell-output 

4. To stay consistent we have to add this to  too.

If you modify the var names to be compliant with the code style, I will merge this and we can try to make it beautiful by removing colours on windows or maybe we find a solution to get them working in curses.

Best regards,
Oliver

**Comment by oliver-zehentleitner** [comment]
I downloaded your fork and tryed to create an example like `examples_curses.py` with your code suggestion and `import curses` but all I get is a black screen.

Can you add an example file to your fork please?

**Comment by oliver-zehentleitner** [comment]
I want to create an image of the print_summary() output and make it available via webserver and include it in the README on Github. And now I have to make the same change as you did... Even if this PR is not ready, i merge it - or I would create a conflict with your PR...

**Comment by oliver-zehentleitner** [comment]
I have rewritten the var names and added some code. 
Removing colors on windows is implemented but not tested...

**Comment by DaWe35** [comment]
Hey!

Thank you, and thanks for the review. I'll test it on windows tomorrow :)

**Comment by DaWe35** [comment]
You can find an example here (it's not updated, it uses the wrong-style disablePrint): https://github.com/DaWe35/Binance-websocket-api-to-mysql/tree/courses

**Comment by oliver-zehentleitner** [comment]
Thanks will try.

Thats why i needed to pull fast :)
https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api#demo

**Pull request merged**
