### PR TITLE
curses example

### PR DESCRIPTION
**Pull request by DaWe35**
## Description

Discussed in #48 

## How Has This Been Tested

Tested on Win 10

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the 
**[CONTRIBUTING](https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/master/CONTRIBUTING.md)** 
document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by oliver-zehentleitner** [comment]
I downloaded the example from your branch and get this error:

```
oliver@valkyrie ~/pyCharmProjects/unicorn-binance-websocket-api $ ./example_curses.py 
Traceback (most recent call last):
  File "./example_curses.py", line 121, in <module>
    wrapper(main)
  File "/opt/anaconda/anaconda/lib/python3.7/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "./example_curses.py", line 117, in main
    display.addstr(0, 0, summary)
_curses.error: addwstr() returned ERR
```
i run it in bash on linux mint.
Are you able to run it on linux?

**Comment by DaWe35** [comment]
> 
> 
> I downloaded the example from your branch and get this error:
> 
> ```
> oliver@valkyrie ~/pyCharmProjects/unicorn-binance-websocket-api $ ./example_curses.py 
> Traceback (most recent call last):
>   File "./example_curses.py", line 121, in <module>
>     wrapper(main)
>   File "/opt/anaconda/anaconda/lib/python3.7/curses/__init__.py", line 94, in wrapper
>     return func(stdscr, *args, **kwds)
>   File "./example_curses.py", line 117, in main
>     display.addstr(0, 0, summary)
> _curses.error: addwstr() returned ERR
> ```
> 
> i run it in bash on linux mint.
> Are you able to run it on linux?

I think you get this error when the window size is too small. Can you retry in maximized window? I really don't know how to solve it...

**Comment by DaWe35** [comment]
Ok I have an idea

**Comment by DaWe35** [comment]
Okay, now it works on small window

**Comment by DaWe35** [comment]
I found another problem (besides the colors), curses just cut the last character of every line.

**Comment by DaWe35** [comment]
Okay, I'm getting a black screen with Ubuntu/Putty

**Comment by oliver-zehentleitner** [comment]
I have to read about curses, atm i have no knowledge about it.

1. If last char gets removed, we can add one extra char at the end of every line that can get removed and will not be missed. But maybe there is a more elegant solution like a parameter (need reading the docs)
2. I would try to make a new method like `curses_summary()` that can be used instead of `print_summary()`
3. It must be stable without errors on windows and unix.

I dont know, do you want to do this together or do you like to try it your self?

**Comment by oliver-zehentleitner** [comment]
One more suggestion, can you create an `example_curses.py` file? If it works fine, we can update other example files.

**Comment by DaWe35** [comment]
Okay thanks, I'll try tomorrow and ask you if I fail.

**Comment by DaWe35** [comment]
Okay, it needs more testing & doc reading, we found more bugs than I expected. I have to postpone the task until later, cause I have a lot of urgent work now.

**Comment by oliver-zehentleitner** [comment]
No worries! Lets make it uncomplicated, work on it as you like it and when its ready we merge it.

I am happy about your contributions!  THANKS!

**Pull request closed without merging**
